# Generated by Django 3.2.19 on 2023-06-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_rename_perro_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
