# Generated by Django 3.2.19 on 2023-07-12 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_cliente_nacionalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
