# Generated by Django 3.2.19 on 2023-07-14 19:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_cliente_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='descripcion',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
