# Generated by Django 3.2.19 on 2023-08-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_cliente_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha',
            field=models.IntegerField(null=True),
        ),
    ]
