# Generated by Django 3.2.19 on 2023-08-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0007_cliente_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
