# Generated by Django 3.2.19 on 2023-08-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0008_alter_cliente_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
    ]
