# Generated by Django 3.2.19 on 2023-08-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoextra',
            name='edad',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
